import type { NextPage } from "next";
import Head from "next/head";

const Demo: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Demo</div>
    </div>
  );
};

export default Demo;
